[project]
name = "cv-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "click>=8.1.7",
    "faiss-cpu>=1.12.0",
    "openai>=1.104.2",
    "pydantic>=2.6.0",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.0.1",
    "sentence-transformers>=5.1.2",
    "streamlit>=1.51.0",
]

[project.scripts]
cv-search = "cli.main:cli"

[project.gui-scripts]
app = "gui.launcher:main"


[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"


